[build]
  command = "npm install && npm run build"
  functions = "functions"
  publish = "public/"
[dev]
  command = "npm install && npm run build" # Command to start your dev server
  publish = "public/" # If you use a _redirect file, provide the path to your static content folder